### ISSUE TITLE
for api 9 & above

### ISSUE THREAD

**Issue by pitambar** [laaptu/appwidget-listview#1]
hi,
this is an nice example to start working with widget, but i want to use this code for api 9 & above so what changes to do, because when i run the same code the on api 10, my app forced colsed, please suggest i have done R&D but no use..

**Comment by laaptu** [comment]
@pitambar : Hi there,I have written this for Android 10 and above because they only support ListView widgets. Could you state the force close error,then only I can help you.

**Comment by pitambar** [comment]
thnx 4 repliyng.
ya this is the logcat ,
12-10 09:54:46.203: E/dalvikvm(240): Could not find class 'android.app.AppOpsManager', referenced from method axp.a
12-10 09:54:46.203: W/dalvikvm(240): VFY: unable to resolve check-cast 386 (Landroid/app/AppOpsManager;) in Laxp;
12-10 09:54:46.218: I/ActivityManager(117): Start proc com.evernote.skitch for broadcast com.evernote.skitch/.app.PackageAddRemoveReceiver: pid=1389 uid=10108 gids={1015, 3003}
12-10 09:54:46.308: I/GetJar SDK [com.zeptolab.ctr.ads](1366): GetJarConfig()::getInstance() -- creating a new GetJarConfig instance for appToken=b2cee90d-4ec4-415b-f36b-7c8a5a0a0fdc
12-10 09:54:46.562: W/dalvikvm(1243): VFY: unable to resolve static field 1115 (CONTENT_MAX_DIMENSIONS_URI) in Landroid/provider/ContactsContract$DisplayPhoto;
12-10 09:54:46.562: W/dalvikvm(1243): VFY: unable to resolve static field 1117 (CONTENT_RAW_CONTACTS_URI) in Landroid/provider/ContactsContract$Profile;
12-10 09:54:46.796: W/dalvikvm(1243): VFY: unable to resolve static field 1121 (CONTENT_URI) in Landroid/provider/ContactsContract$StreamItems;
12-10 09:54:46.875: W/dalvikvm(1243): VFY: unable to resolve static field 1117 (CONTENT_RAW_CONTACTS_URI) in Landroid/provider/ContactsContract$Profile;
12-10 09:54:46.914: W/dalvikvm(1243): VFY: unable to resolve static field 1120 (CONTENT_LIMIT_URI) in Landroid/provider/ContactsContract$StreamItems;
12-10 09:54:46.925: W/dalvikvm(1243): VFY: unable to resolve static field 1117 (CONTENT_RAW_CONTACTS_URI) in Landroid/provider/ContactsContract$Profile;
12-10 09:54:47.140: I/dalvikvm(1243): Could not find method android.net.TrafficStats.setThreadStatsTag, referenced from method nv.run
12-10 09:54:47.140: W/dalvikvm(1243): VFY: unable to resolve static method 2831: Landroid/net/TrafficStats;.setThreadStatsTag (I)V
12-10 09:54:47.253: I/NativeLibrarySupport(1195): Native networking disabled
12-10 09:54:47.464: I/dalvikvm(1195): Could not find method android.net.TrafficStats.setThreadStatsTag, referenced from method qk.run
12-10 09:54:47.476: W/dalvikvm(1195): VFY: unable to resolve static method 4124: Landroid/net/TrafficStats;.setThreadStatsTag (I)V
12-10 09:54:47.574: E/Setting(1265): Intent Action android.intent.action.MEDIA_SCANNER_STARTED
12-10 09:54:47.656: I/ActivityManager(117): Start proc com.android.providers.calendar for content provider com.android.providers.calendar/.CalendarProvider2: pid=1454 uid=10026 gids={3003}
12-10 09:54:47.808: I/System.out(988): [INFO:24067]: f: Running flush
12-10 09:54:47.828: I/ActivityManager(117): No longer want com.cooliris.media (pid 1179): hidden #16
12-10 09:54:47.863: I/dalvikvm(1243): Could not find method android.database.sqlite.SQLiteOpenHelper.onDowngrade, referenced from method ctr.onDowngrade
12-10 09:54:47.863: W/dalvikvm(1243): VFY: unable to resolve virtual method 2501: Landroid/database/sqlite/SQLiteOpenHelper;.onDowngrade (Landroid/database/sqlite/SQLiteDatabase;II)V
12-10 09:54:47.910: I/System.out(988): [INFO:24171]: f: Sending payload [bytes=272]
12-10 09:54:47.949: E/GCM(1252): Received error AUTHENTICATION_FAILED
12-10 09:54:47.953: E/Pulse - UALib(1252): Received GCM error: AUTHENTICATION_FAILED
12-10 09:54:47.953: E/Pulse - UALib(1252): Failed to register with GCM.
12-10 09:54:47.953: E/Pulse - UALib(1252): GCM Failure: AUTHENTICATION_FAILED
12-10 09:54:48.066: I/ActivityThread(1454): Pub com.android.calendar: com.android.providers.calendar.CalendarProvider2
12-10 09:54:48.089: I/GetJar SDK [com.zeptolab.ctr.ads](1366): GetJarConfig()::getInstance() -- re-using existing GetJarConfig instance for appToken=b2cee90d-4ec4-415b-f36b-7c8a5a0a0fdc
12-10 09:54:48.109: I/ActivityManager(117): Start proc com.wordpress.laaptu for broadcast com.wordpress.laaptu/.WidgetProvider: pid=1470 uid=10210 gids={}
12-10 09:54:48.152: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: startWorker() [thread:11] startWorker()
12-10 09:54:48.175: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: startWorker() [thread:11] Thread started
12-10 09:54:48.187: E/dalvikvm(1243): Could not find class 'android.os.UserManager', referenced from method aod.b
12-10 09:54:48.187: W/dalvikvm(1243): VFY: unable to resolve check-cast 623 (Landroid/os/UserManager;) in Laod;
12-10 09:54:48.187: I/dalvikvm(1243): Could not find method android.accounts.AccountManager.getAccountsByTypeForPackage, referenced from method aod.c
12-10 09:54:48.187: W/dalvikvm(1243): VFY: unable to resolve virtual method 1804: Landroid/accounts/AccountManager;.getAccountsByTypeForPackage (Ljava/lang/String;Ljava/lang/String;)[Landroid/accounts/Account;
12-10 09:54:48.187: E/dalvikvm(1243): Could not find class 'android.os.UserManager', referenced from method aod.c
12-10 09:54:48.187: W/dalvikvm(1243): VFY: unable to resolve check-cast 623 (Landroid/os/UserManager;) in Laod;
12-10 09:54:48.191: E/dalvikvm(1243): Could not find class 'android.os.UserManager', referenced from method aod.d
12-10 09:54:48.191: W/dalvikvm(1243): VFY: unable to resolve check-cast 623 (Landroid/os/UserManager;) in Laod;
12-10 09:54:48.316: W/dalvikvm(988): No implementation found for native Lcom/carrieriq/iqagent/client/NativeClient;.clientInit (Ljava/lang/Object;)I
12-10 09:54:48.332: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: access$300() [thread:13] Worker Thread is waiting to be notified
12-10 09:54:48.394: I/ActivityManager(117): No longer want com.path (pid 1099): hidden #16
12-10 09:54:48.710: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: access$300() [thread:13] Worker Thread is awake
12-10 09:54:48.742: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: processesRequest() [thread:15] [request:1315057034] Starting Request 1315057034
12-10 09:54:48.757: W/dalvikvm(1195): VFY: unable to resolve instance field 1911
12-10 09:54:48.781: I/GetJar SDK [com.zeptolab.ctr.ads](1366): CommManager: access$300() [thread:13] Worker Thread is waiting to be notified
12-10 09:54:48.937: W/dalvikvm(1470): Unable to resolve superclass of Lcom/wordpress/laaptu/WidgetService; (527)
12-10 09:54:48.937: W/dalvikvm(1470): Link of class 'Lcom/wordpress/laaptu/WidgetService;' failed
12-10 09:54:48.937: E/dalvikvm(1470): Could not find class 'com.wordpress.laaptu.WidgetService', referenced from method com.wordpress.laaptu.WidgetProvider.updateWidgetListView
12-10 09:54:48.937: W/dalvikvm(1470): VFY: unable to resolve const-class 555 (Lcom/wordpress/laaptu/WidgetService;) in Lcom/wordpress/laaptu/WidgetProvider;
12-10 09:54:48.941: W/dalvikvm(1470): threadid=1: thread exiting with uncaught exception (group=0x40015578)
12-10 09:54:48.957: E/AndroidRuntime(1470): FATAL EXCEPTION: main
12-10 09:54:48.957: E/AndroidRuntime(1470): java.lang.NoClassDefFoundError: com.wordpress.laaptu.WidgetService
12-10 09:54:48.957: E/AndroidRuntime(1470):     at com.wordpress.laaptu.WidgetProvider.updateWidgetListView(WidgetProvider.java:49)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at com.wordpress.laaptu.WidgetProvider.onUpdate(WidgetProvider.java:33)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:61)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:1798)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.app.ActivityThread.access$2400(ActivityThread.java:117)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:985)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.os.Looper.loop(Looper.java:130)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at android.app.ActivityThread.main(ActivityThread.java:3687)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at java.lang.reflect.Method.invokeNative(Native Method)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at java.lang.reflect.Method.invoke(Method.java:507)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
12-10 09:54:48.957: E/AndroidRuntime(1470):     at dalvik.system.NativeStart.main(Native Method)
12-10 09:54:48.988: E/(117): Dumpstate > /data/log/dumpstate_app_error
12-10 09:54:49.000: I/dumpstate(1487): begin
12-10 09:54:49.003: E/InfoAlarmWidgetScheduler(1223): AllDay Event Count = 0
12-10 09:54:49.117: I/PeopleDatabaseHelper(1243): cleanUpNonGplusAccounts done.
12-10 09:54:49.289: E/InfoAlarmWidgetScheduler(1223): 1 : Calendar_count = 0
12-10 09:54:50.746: W/System.err(601): java.net.UnknownHostException: na-snsgw.samsungmobile.com
12-10 09:54:50.746: W/System.err(601):  at java.net.InetAddress.lookupHostByName(InetAddress.java:508)
12-10 09:54:50.746: W/System.err(601):  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
12-10 09:54:50.746: W/System.err(601):  at java.net.InetAddress.getAllByName(InetAddress.java:256)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:136)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:436)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
12-10 09:54:50.746: W/System.err(601):  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
12-10 09:54:50.746: W/System.err(601):  at com.sec.android.app.sns.http.SnsHttpSendingThread.doSendHttp(SnsHttpMgr.java:530)
12-10 09:54:50.746: W/System.err(601):  at com.sec.android.app.sns.http.SnsHttpSendingThread.run(SnsHttpMgr.java:453)
12-10 09:54:50.746: W/System.err(601):  at java.lang.Thread.run(Thread.java:1019)
12-10 09:54:50.746: E/SNS_HTTPMGR(601): SnsHttpSendingThread : doSendHttp() : UnknownHostException
12-10 09:54:50.746: E/SNS_HTTPMGR(601): java.net.UnknownHostException: na-snsgw.samsungmobile.com
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at java.net.InetAddress.lookupHostByName(InetAddress.java:508)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at java.net.InetAddress.getAllByName(InetAddress.java:256)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:136)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:436)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at com.sec.android.app.sns.http.SnsHttpSendingThread.doSendHttp(SnsHttpMgr.java:530)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at com.sec.android.app.sns.http.SnsHttpSendingThread.run(SnsHttpMgr.java:453)
12-10 09:54:50.746: E/SNS_HTTPMGR(601):     at java.lang.Thread.run(Thread.java:1019)
12-10 09:54:50.750: I/SNS_FRAMEWORK(601): SnsFramework : processResponse() : Enter Well~
12-10 09:54:50.777: E/SNS_FRAMEWORK(601): SnsFramework : processResponse() : Network Unavailable !!!
12-10 09:54:50.777: E/SNS_FRAMEWORK(601): com.sec.android.app.sns.exception.SnsNetworkException: HTTP StatusCode error : httpStatusCode[1009]
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at com.sec.android.app.sns.framework.SnsFramework.processResponse(SnsFramework.java:968)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at com.sec.android.app.sns.SnsService$1.handleMessage(SnsService.java:109)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at android.os.Looper.loop(Looper.java:130)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at android.app.ActivityThread.main(ActivityThread.java:3687)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at java.lang.reflect.Method.invokeNative(Native Method)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at java.lang.reflect.Method.invoke(Method.java:507)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
12-10 09:54:50.777: E/SNS_FRAMEWORK(601):   at dalvik.system.NativeStart.main(Native Method)
12-10 09:54:51.027: I/InputReader(117): dispatchTouch::touch event's action is 0
12-10 09:54:51.027: I/InputDispatcher(117): Delivering touch to current input target: action: 0, channel '40ab1190 com.sec.android.app.twlauncher/com.sec.android.app.twlauncher.Launcher (server)'
12-10 09:54:51.132: I/InputReader(117): dispatchTouch::touch event's action is 1
12-10 09:54:51.132: I/InputDispatcher(117): Delivering touch to current input target: action: 1, channel '40ab1190 com.sec.android.app.twlauncher/com.sec.android.app.twlauncher.Launcher (server)'
12-10 09:54:51.234: I/SNS_FRAMEWORK(601): SnsFramework : processResponse(), reqID = 0, reqCount = 0, reqGeneratorState = 0
12-10 09:54:52.488: I/System.out(240): [INFO:64762]: LogSource: Sending payload [bytes=464]
12-10 09:54:52.488: I/System.out(240): [SEVERE:64763]: LogSource: AsyncHttpRequestImpl.run(): exception thrown : www.google.com: java.net.UnknownHostException
12-10 09:54:52.578: I/InputReader(117): dispatchTouch::touch event's action is 0
12-10 09:54:52.578: I/InputDispatcher(117): Delivering touch to current input target: action: 0, channel '40ab1190 com.sec.android.app.twlauncher/com.sec.android.app.twlauncher.Launcher (server)'
12-10 09:54:52.914: I/System.out(988): [INFO:29171]: f: Running delayed flush
12-10 09:54:52.921: I/System.out(988): [INFO:29182]: f: Running flush
12-10 09:54:53.507: I/dumpstate(1487): done
12-10 09:54:53.578: I/ActivityManager(117): No longer want com.google.android.googlequicksearchbox (pid 1143): hidden #16
12-10 09:54:53.652: E/BatteryPolicy(172): onReceive intent:Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000000 (has extras) }
12-10 09:54:53.746: I/Launcher(216): onWindowFocusChanged(false)
12-10 09:54:53.902: I/InputReader(117): dispatchTouch::touch event's action is 1
12-10 09:54:53.902: I/InputDispatcher(117): Delivering touch to current input target: action: 1, channel '40ab1190 com.sec.android.app.twlauncher/com.sec.android.app.twlauncher.Launcher (server)'
12-10 09:54:54.085: I/dalvikvm(240): Could not find method android.app.PendingIntent.getCreatorPackage, referenced from method ahw.b
12-10 09:54:54.097: I/GetJar SDK [com.zeptolab.ctrexperiments.ads](1354): GetJarConfig()::getInstance() -- re-using existing GetJarConfig instance for appToken=04fa399f-b9a4-48cd-902d-b248bb63aef6
12-10 09:54:54.109: W/dalvikvm(240): VFY: unable to resolve virtual method 2022: Landroid/app/PendingIntent;.getCreatorPackage ()Ljava/lang/String;
12-10 09:54:54.109: I/dalvikvm(240): Could not find method android.app.PendingIntent.getCreatorUid, referenced from method ahw.a
12-10 09:54:54.109: W/dalvikvm(240): VFY: unable to resolve virtual method 2023: Landroid/app/PendingIntent;.getCreatorUid ()I
12-10 09:54:54.160: I/ActivityManager(117): No longer want imoblife.memorybooster.lite (pid 1309): hidden #16
12-10 09:54:54.601: I/Database(198): sqlite returned: error code = 17, msg = prepared statement aborts at 18: [SELECT MAX(_id) FROM images]
12-10 09:54:54.796: E/MTP-LAUNCHER(216): Action : file:///mnt/sdcard
12-10 09:54:54.808: I/MediaProvider(198): MediaScanner stopped!!!
12-10 09:54:54.820: I/ActivityManager(117): Start proc com.cooliris.media for broadcast com.cooliris.media/com.cooliris.cache.BootReceiver: pid=1513 uid=10062 gids={1015, 3003, 1001}
12-10 09:54:54.972: I/ActivityThread(1513): Pub com.cooliris.picasa.contentprovider: com.cooliris.picasa.PicasaContentProvider
12-10 09:54:55.000: E/MTP-LAUNCHER(216): media scanning finished,  status.:: 0
12-10 09:54:55.062: I/TEST(1513): Got intent with action Intent { act=android.intent.action.MEDIA_SCANNER_FINISHED dat=file:///mnt/sdcard cmp=com.cooliris.media/com.cooliris.cache.BootReceiver (has extras) }
12-10 09:54:55.097: I/InputReader(117): dispatchTouch::touch event's action is 0
12-10 09:54:55.101: I/InputDispatcher(117): Delivering touch to current input target: action: 0, channel '40b4a868 Sorry! (server)'
12-10 09:54:55.117: I/MediaScannerService(198): !@endofMediascannerservice
12-10 09:54:55.132: I/CacheService(1513): restartThread() threadRef = null, name = CacheRefresh
12-10 09:54:55.132: I/CacheService(1513): Refreshing cache.
12-10 09:54:55.132: E/DiskCache(1513): Delete All Cache Files!!!
12-10 09:54:55.152: I/CacheService(1513): onHandleIntent Intent { act=com.cooliris.cache.action.CACHE cmp=com.cooliris.media/com.cooliris.cache.CacheService (has extras) }
12-10 09:54:55.156: E/DiskCache(1513): Delete All Cache Files!!!
12-10 09:54:55.179: I/CacheService(1513): Building albums.
12-10 09:54:55.187: W/DiskCache(1513): replace to chunk /mnt/sdcard/Android/data/com.cooliris.media/cache/local-album-cache/chunk_0 size 10>10
12-10 09:54:55.187: I/CacheService(1513): restartThread() threadRef = Thread[CacheRefresh,5,main], name = CacheRefresh
12-10 09:54:55.199: I/CacheService(1513): restartThread() threadRef = null, name = ThumbnailRefresh
12-10 09:54:55.199: I/CacheService(1513): Refreshing cache.
12-10 09:54:55.207: I/InputReader(117): dispatchTouch::touch event's action is 1
12-10 09:54:55.207: I/InputDispatcher(117): Delivering touch to current input target: action: 1, channel '40b4a868 Sorry! (server)'
12-10 09:54:55.218: I/Launcher(216): onWindowFocusChanged(true)
12-10 09:54:55.218: E/Launcher(216): setWindowOpaque()
12-10 09:54:55.238: I/Process(1470): Sending signal. PID: 1470 SIG: 9
12-10 09:54:55.253: W/InputManagerService(117): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@40795038
12-10 09:54:55.265: I/ActivityManager(117): No longer want com.gameloft.android.ANMP.GloftUFHM:remote (pid 1320): hidden #16
12-10 09:54:55.343: I/ActivityManager(117): Process com.wordpress.laaptu (pid 1470) has died.
12-10 09:54:55.386: W/DiskCacheSEC(1513): loadIndex /mnt/sdcard/Android/data/com.cooliris.media/cache/local-image-thumbs/index
12-10 09:54:55.394: E/DiskCacheSEC(1513): checksum not matched -- wanted: 886318438, got: 305441741
12-10 09:54:55.398: E/DiskCache(1513): Delete All Cache Files!!!
12-10 09:54:55.468: E/DiskCache(1513): Delete All Cache Files!!!
12-10 09:54:55.492: I/CacheService(1513): Building albums.
12-10 09:54:55.523: I/CacheService(1513): Done building albums.
12-10 09:54:55.523: I/CacheService(1513): Building items.
12-10 09:54:55.531: I/CacheService(1513): cursorImages.getCount() 2
12-10 09:54:55.531: I/CacheService(1513): cursorVideos.getCount() 4
12-10 09:54:55.546: I/CacheService(1513): Done building items.
12-10 09:54:55.550: I/GLSUser(240): Method not found getActionBar
12-10 09:54:55.554: I/GLSUser(240): Method not found hasPermanentMenuKey
12-10 09:54:55.554: I/GLSUser(240): Method not found setShowAsAction
12-10 09:54:55.554: I/GLSUser(240): Class not found android.app.ActionBar
12-10 09:54:55.554: I/GLSUser(240): Class not found android.app.ActionBar
12-10 09:54:55.554: I/GLSUser(240): Method not found setThreadStatsTag
12-10 09:54:55.554: I/GLSUser(240): Method not found clearThreadStatsTag
12-10 09:54:55.554: I/GLSUser(240): Class not found android.app.ActionBar
12-10 09:54:55.562: I/GLSUser(240): Method not found setSystemUiVisibility
12-10 09:54:56.597: I/GetJar SDK [com.zeptolab.ctr.ads](1366): GetJarConfig()::getInstance() -- re-using existing GetJarConfig instance for appToken=b2cee90d-4ec4-415b-f36b-7c8a5a0a0fdc
12-10 09:54:57.304: W/DiskCacheSEC(1513): loadIndex /mnt/sdcard/Android/data/com.cooliris.media/cache/local-image-thumbs/index
12-10 09:54:57.320: E/DiskCacheSEC(1513): [SE Lab.] expired sd #: 0
12-10 09:54:57.324: W/UriTexture(1513): create URI_CACHE = /mnt/sdcard/Android/data/com.cooliris.media/cache/hires-image-cache/
12-10 09:54:57.523: W/DiskCacheSEC(1513): enter writeIndex 2
12-10 09:54:57.527: W/DiskCacheSEC(1513): Create TempFile = /sdcard/DiskCacheIndex2111140947.tmp
12-10 09:54:57.542: W/DiskCacheSEC(1513): rename to = /mnt/sdcard/Android/data/com.cooliris.media/cache/local-image-thumbs/index
12-10 09:55:02.800: I/GetJar SDK [com.zeptolab.ctrexperiments.ads](1354): GetJarConfig()::getInstance() -- re-using existing GetJarConfig instance for appToken=04fa399f-b9a4-48cd-902d-b248bb63aef6
12-10 09:55:06.695: I/GetJar SDK [com.zeptolab.ctr.ads](1366): GetJarConfig()::getInstance() -- re-using existing GetJarConfig instance for appToken=b2cee90d-4ec4-415b-f36b-7c8a5a0a0fdc
12-10 09:55:07.824: E/GlsClient-query(988): requestFailed
12-10 09:55:07.824: E/GlsClient-query(988): ay.g
12-10 09:55:07.824: E/GlsClient-query(988):     at ay.d.t(Unknown Source)
12-10 09:55:07.824: E/GlsClient-query(988):     at ay.b.a(Unknown Source)
12-10 09:55:07.824: E/GlsClient-query(988):     at Z.b.g(Unknown Source)
12-10 09:55:07.824: E/GlsClient-query(988):     at Z.a.g(Unknown Source)
12-10 09:55:07.824: E/GlsClient-query(988):     at Z.d.run(Unknown Source)
12-10 09:55:07.824: E/GlsClient-query(988):     at aE.d.run(Unknown Source)
12-10 09:55:08.136: I/ActivityManager(117): Start proc com.sprint.w.installer for service com.sprint.w.installer/.delivery.ReportPostService: pid=1535 uid=10042 gids={3003, 1015}
12-10 09:55:08.273: I/ActivityThread(1535): Pub com.sprint.installer: com.sprint.w.installer.ContentProvider
12-10 09:55:08.273: I/ActivityThread(1535): Pub com.sprint.w.installer.SuggestProvider: com.sprint.w.installer.SearchSuggestProvider
12-10 09:55:20.625: W/System.err(1342): java.net.UnknownHostException: geminidev.gotoip3.com
12-10 09:55:20.625: W/System.err(1342):     at java.net.InetAddress.lookupHostByName(InetAddress.java:508)
12-10 09:55:20.625: W/System.err(1342):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
12-10 09:55:20.625: W/System.err(1342):     at java.net.InetAddress.getAllByName(InetAddress.java:256)
12-10 09:55:20.628: W/System.err(1342):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:136)
12-10 09:55:20.628: W/System.err(1342):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
12-10 09:55:20.632: W/System.err(1342):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
12-10 09:55:20.632: W/System.err(1342):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:436)
12-10 09:55:20.632: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
12-10 09:55:20.636: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
12-10 09:55:20.636: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
12-10 09:55:20.636: W/System.err(1342):     at com.a.d.a.f.f.a(Unknown Source)
12-10 09:55:20.640: W/System.err(1342):     at com.a.d.c.m.b(Unknown Source)
12-10 09:55:20.640: W/System.err(1342):     at com.a.d.a.f.b.run(Unknown Source)
12-10 09:55:20.640: W/System.err(1342): java.net.UnknownHostException: geminidev.gotoip3.com
12-10 09:55:20.644: W/System.err(1342):     at java.net.InetAddress.lookupHostByName(InetAddress.java:508)
12-10 09:55:20.644: W/System.err(1342):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
12-10 09:55:20.644: W/System.err(1342):     at java.net.InetAddress.getAllByName(InetAddress.java:256)
12-10 09:55:20.648: W/System.err(1342):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:136)
12-10 09:55:20.648: W/System.err(1342):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
12-10 09:55:20.652: W/System.err(1342):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
12-10 09:55:20.652: W/System.err(1342):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:436)
12-10 09:55:20.656: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
12-10 09:55:20.664: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
12-10 09:55:20.664: W/System.err(1342):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
12-10 09:55:20.667: W/System.err(1342):     at com.a.d.a.f.f.a(Unknown Source)
12-10 09:55:20.667: W/System.err(1342):     at com.a.d.c.m.b(Unknown Source)
12-10 09:55:20.667: W/System.err(1342):     at com.a.d.a.f.b.run(Unknown Source)
12-10 09:55:20.671: W/System.err(1342): java.net.UnknownHostException: geminidev.gotoip3.com
12-10 09:55:20.671: W/System.err(1342):     at java.net.InetAddress.lookupHostByName(InetAddress.java:508)

what to do in this case,

**Comment by laaptu** [comment]
Hello @pitambar  could you just filter out the error thrown by the app widget list view as it seems you are exposing all the unwanted log as welll
